"""Wine-specific validation rules."""

from __future__ import annotations

from app.validators.rules.class_type import make_validate_class_type


_WINE_VARIETALS = [
    "cabernet sauvignon",
    "cabernet franc",
    "merlot",
    "pinot noir",
    "pinot grigio",
    "pinot gris",
    "chardonnay",
    "sauvignon blanc",
    "riesling",
    "gewürztraminer",
    "gewurztraminer",
    "syrah",
    "shiraz",
    "malbec",
    "zinfandel",
    "petite sirah",
    "petite verdot",
    "sangiovese",
    "nebbiolo",
    "tempranillo",
    "grenache",
    "mourvedre",
    "mourvèdre",
    "carignan",
    "cinsault",
    "viognier",
    "marsanne",
    "rousanne",
    "chenin blanc",
    "semillon",
    "sémillon",
    "muscat",
    "moscato",
    "riesling",
    "albariño",
    "albarino",
    "verdejo",
    "torrontés",
    "torrontes",
    "pinotage",
    "barbera",
    "dolcetto",
    "montepulciano",
    "corvina",
    "blaufränkisch",
    "blaufrankisch",
    "grüner veltliner",
    "gruner veltliner",
    "rosé",
    "rose",
    "port",
    "sherry",
    "bordeaux blend",
    "rhône blend",
    "rhone blend",
    "champagne",
    "prosecco",
    "cava",
    "cremant",
    "crémant",
    "sparkling",
]


validate_wine_class_type = make_validate_class_type(
    lexicon=_WINE_VARIETALS,
    label="wine varietal",
)
